name: ETL Pipeline
on:
  schedule:
    - cron: "0 20 * * *"  # Runs at 20:00 UTC (06:00 AEST) daily
  workflow_dispatch:

jobs:
  run-etl:
    environment: production
    runs-on: [self-hosted, macOS, ARM64]
    env:
      HOME: ${{ github.workspace }}
      RUNNER_TOOL_CACHE: ${{ github.workspace }}/_tool
      RUNNER_TEMP: ${{ github.workspace }}/_temp
      AGENT_TOOLSDIRECTORY: ${{ github.workspace }}/_tool
    steps:
      - name: Prepare runner directories
        run: |
          mkdir -p "$RUNNER_TOOL_CACHE" "$RUNNER_TEMP" "$HOME"
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
        env:
          AGENT_TOOLSDIRECTORY: ${{ github.workspace }}/_tool
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright Browsers
        run: |
          # Ensure Playwright Chromium is installed for VisionTwitterExtractor
          playwright install chromium
      
      - name: Validate Secrets
        run: |
          # Check if all required secrets are present
          if [ -z "${{ secrets.FRED_API_KEY }}" ]; then
            echo "Error: FRED_API_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
            echo "Error: SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_KEY }}" ]; then
            echo "Error: SUPABASE_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.TWITTER_EMAIL }}" ]; then
            echo "Error: TWITTER_EMAIL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.TWITTER_USERNAME }}" ]; then
            echo "Error: TWITTER_USERNAME is not set"
            exit 1
          fi
          if [ -z "${{ secrets.TWITTER_PASSWORD }}" ]; then
            echo "Error: TWITTER_PASSWORD is not set"
            exit 1
          fi
          echo "All required secrets are present"
      
      - name: Run ETL
        env:
          # API Keys
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          ALTERNATIVE_API_KEY: ${{ secrets.ALTERNATIVE_API_KEY }}
          
          # Supabase Configuration
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          
          # Google Sheets Configuration
          GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
          GOOGLE_SHEET_WORKSHEET: ${{ secrets.GOOGLE_SHEET_WORKSHEET }}
          
          # Google Service Account
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          
          # OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
          # Twitter credentials
          TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        run: |
          # Create credentials.json from secret with proper JSON formatting
          echo "$GOOGLE_CREDENTIALS" | jq . > credentials.json
          
          # Verify the credentials file was created correctly
          if [ ! -f credentials.json ]; then
            echo "Error: Failed to create credentials.json"
            exit 1
          fi
          
          # Run the ETL pipeline
          python main.py
          
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'ETL Pipeline Failed',
              body: 'The ETL pipeline failed. Please check the workflow run for details.',
              labels: ['bug', 'etl']
            })
